### PR TITLE
Add configuration setting to provide wrapping expression

### PR DESCRIPTION
**Pull request by trevorforrey**
Really love your extension! I find myself wrapping a lot of console logs in JSON.stringify, so I added a configuration to add a wrapping expression around the logged value. 

Screen Shot 2019-08-10 at 8 03 43 PM

Screen Shot 2019-08-10 at 8 04 46 PM

### CODE REVIEW

**Comment by LuisEGR** [comment]
Thank you!, that's really useful.

**Comment by LuisEGR** [comment]
I had some troubles with vsce when publishing the extension and accidentally deleted my publisher, this is already in the store, but aparently it is required to reinstall the extension, because the other one is not in the store anymore :c

**Comment by trevorforrey** [comment]
Oh no! Is there anything I can do to help publish it?

**Comment by LuisEGR** [comment]
don't worry, it's already published, just the install number got reset:
https://marketplace.visualstudio.com/items?itemName=Luis.console-log

**Pull request merged**
